name: maven
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          9,    # Minimum supported version
          16,   # Minecraft >= 1.17 (used now)
        ]
        # and run on both Linux and Windows
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - name: Build with Maven
        run: |
          curl -O https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar
          cd strongholdconfig
          mvn clean install -f pom.xml
      - name: Upload shaded artifact
        uses: actions/upload-artifact@v2
        if: ${{ matrix.java == 9 && matrix.os == 'ubuntu-latest' }}
        with:
          name: shaded-plugin-artifact
          path: strongholdconfig/target/StrongholdConfig-*.jar
